# Python script for guessing random number generated by the computer

import random
import art

def guess_num():
    print(art.logo)
    print("Welcome to the Number Guessing Game!\n")
    print("I'm thinking of a number between 1 and 100.\n")
    difficulty = input("Choose a difficulty. Type 'easy' or 'hard': ")
    number = random.randint(1, 100)
    if difficulty == 'easy':
        total_chance = 10
        print(f"\nYou have {total_chance} attempts remaining to guess the number.")
        guess = int(input("Make a guess: "))
        while total_chance > 1:
            if guess > number:
                print("Too high")
            elif guess < number:
                print("Too low")
            else:
                break
            print("Guess again.\n")
            total_chance -= 1
            print(f"You have {total_chance} attempts remaining to guess the number.")
            guess = int(input("Make a guess: "))
        if guess == number:
            print("\nYou guessed it correctly, you win 🥳\n")
        else:
            print("\nYou've run out of guesses, you lose 😢\n")
    elif difficulty == 'hard':
        total_chance = 5
        print(f"\nYou have {total_chance} attempts remaining to guess the number.")
        guess = int(input("Make a guess: "))
        while total_chance > 1:
            if guess > number:
                print("Too high")
            elif guess < number:
                print("Too low")
            else:
                break
            print("Guess again.\n")
            total_chance -= 1
            print(f"You have {total_chance} attempts remaining to guess the number.")
            guess = int(input("Make a guess: "))
        if guess == number:
            print("\nYou guessed it correctly, you win 🥳\n")
        else:
            print("\nYou've run out of guesses, you lose 😢\n")


if __name__ == '__main__':
    guess_num()